# first get refresh token
GET https://api.imgur.com/oauth2/authorize?client_id=7cd2c86728bbcc2&response_type=token

###

# get Access Token
POST https://api.imgur.com/oauth2/token
Content-Type: application/json

{
  "refresh_token": "570ab1910045d8584c7be15bc26c439304a76312",
  "client_id": "7cd2c86728bbcc2",
  "client_secret": "d72573168c2083e1ee89a582f66c65de41b90a2c",
  "grant_type": "refresh_token"
}

###

# get Access Token
POST http://localhost:3000/imgur/token
Content-Type: application/json

{}
###

# upload imgur image
POST http://localhost:3000/imgur/image
Content-Type: application/json

{
  "coverUrl": "https://media.istockphoto.com/id/1952691908/photo/kayaking-in-crete.jpg?s=1024x1024&w=is&k=20&c=6DxMHmM-sqVKLIrkdvFO8BvV9e5EWjpXB30VEaW0Qyc="
}

###